# fly.toml app configuration file generated for salary-management-incubyte on 2026-05-17T13:51:34Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'salary-management-incubyte'
primary_region = 'ams'

[build]
  dockerfile = 'Dockerfile'

[env]
  DATABASE_URL = 'sqlite:////data/app.db'

[[mounts]]
  source = 'salary_data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '5s'
    method = 'GET'
    path = '/health'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
